### ISSUE TITLE
'No cores available' for sitecore-solr:8.2.180406-nanoserver-1803

### ISSUE THREAD

**Issue by sshushliapin** [sitecoreops/sitecore-images#11]
I built images as described in the [README](https://github.com/sitecoreops/sitecore-images#how-to-use) file and trying to run solr for 8.2.7 (rev. 180406) using the following command:
```
docker run -p 8983:8983 <myrepo>/sitecore-solr:8.2.180406-nanoserver-1803
```
The SOLR 6.6.3 is running but there is no cores:
![image](https://user-images.githubusercontent.com/4719165/48494541-c6716b80-e836-11e8-9435-d5bd6c4268bb.png)

Shouldn't the default Sitecore cores be part of the image?

**Comment by pbering** [comment]
Hi, unfortunately it's not supported for Sitecore 8 today. The reason for this is that in Sitecore 9 we can seed default cores using SIF but we can't do that in Sitecore 8 by default. We use this image internally on a customer and here we define a volume mount and place preconfigured cores here, then they will be available.
