### ISSUE TITLE
Windows version 10.0.17763-based image is incompatible with a 10.0.17134 host

### ISSUE THREAD

**Issue by sshushliapin** [sitecoreops/sitecore-images#12]
I'm unable to build SC 9.1 images on my Win 10 Pro (build 17134). Is the OS `ltsc2019` a must for [9.1](https://github.com/sitecoreops/sitecore-images#current-images)?
The error I receive:

```
4.7.2-windowsservercore-ltsc2019: Pulling from dotnet/framework/aspnet
a Windows version 10.0.17763-based image is incompatible with a 10.0.17134 host
```
Docker version:
```
 Version:           18.09.0
 API version:       1.39
```

**Comment by pbering** [comment]
Hi there, as the error states `a Windows version 10.0.17763-based image is incompatible with a 10.0.17134 host` your Windows 10 is too old, so to run ltsc2019 images you need to upgrade to Windows 10 *1809*. As a workaround you can fork this repo and downgrade the images to windows server core 1803 (see the 9.0.2) images as it is not required by 9.1.

**Comment by sshushliapin** [comment]
Ok, forced Windows to check for updates few times (manually). Now it seems it comes:

![image](https://user-images.githubusercontent.com/4719165/50281702-fffe4d80-0458-11e9-9399-7a01b9e9fb03.png)

Thanks, @pbering!
