### ISSUE TITLE
Stopping Solr leaves .lock files behind

### ISSUE THREAD

**Issue by joostmeijles** [sitecoreops/sitecore-images#15]
When I stop my Solr container (using ltsc2019 image & process isolation) the `write.lock` files are not removed. 
This causes a restart of the Solr container to fail.

Is this a known bug?

**Comment by pbering** [comment]
Haven't seen it on 9.0.2 Solr 1803 which is in production. Tested the ltsc2019 variant on Windows 10 using hyperv isolation and didn't see that issues. Can you please try if you can reproduce it using hyperv?

**Comment by joostmeijles** [comment]
Tested; with hyper-v on Windows 10 having (intermittently) the same issue.

**Comment by pbering** [comment]
Just tested on Windows 10 1809 with the 9.0.2 1803 solr with no problems, restarted containers multiple times. I can see that there is a `write.lock` in some cores but they don't seem to give Solr any issues starting up. Can you try to write step by step what you are doing so I can try the same?

**Comment by joostmeijles** [comment]
Steps are quite straightforward:
1. Start Solr container
2. Wait a bit for Solr to start / attach all cores
3. Stop Solr container
4. (Re-) start Solr container with same cores
5. Solr reports locking errors for the core directories that contain `write.lock` files

I have reproduced this intermittently at multiple machines with process- and Hyper-V isolation.
Although using process-isolation seems to trigger this problem more often.

I suspect that, when stopping a Solr container, depending on how quick it ends all processes, the cores correctly stopped.

My current plan is to simply remove any `write.lock` files upon start of the container.

**Comment by pbering** [comment]
in step 3 are you using `stop` or `down`

but anyways, it's a good plan to just wipe all `write.lock` files during startup, could be done in `Boot.cmd`

**Comment by joostmeijles** [comment]
Using `stop` in step 3.

**Comment by pbering** [comment]
was able to reproduce, so I fixed it. Thank you 👍
