### ISSUE TITLE
XP support

### ISSUE THREAD

**Issue by jeanfrancoislarente** [sitecoreops/sitecore-images#3]
Any chance you already have (or plan to have) XP support?

**Comment by pbering** [comment]
Hi, yes the plan is to do more images to support the XP topology, ie. xConnect and also for each of the other roles. I will start with xConnect to support XP0 and then later on the rest for a fully scaled XP. The xConnect image will properly be much like the awesome work done here: https://github.com/avivasolutionsnl/sitecore-docker

**Comment by pbering** [comment]
Sitecore 9.0.2 XP on 1803 just added (also see test compose file: https://github.com/sitecoreops/sitecore-images/blob/master/tests/9.0.2%20rev.%20180604/1803/docker-compose.xp.yml) ! So I'm closing this for now :)
