### ISSUE TITLE
aspnet 4.7.1 vs 4.7.2

### ISSUE THREAD

**Issue by sshushliapin** [sitecoreops/sitecore-images#33]
Currently there are two main [aspnet](https://hub.docker.com/_/microsoft-dotnet-framework-aspnet) versions used in this repository:
- 4.7.1 is used for images based on win 1709 (e.g. [8.2.3](https://github.com/sitecoreops/sitecore-images/blob/master/images/8.2%20rev.%20170407/windowsservercore-1709/Dockerfile#L2), [8.2.4](https://github.com/sitecoreops/sitecore-images/blob/master/images/8.2%20rev.%20170614/windowsservercore-1709/Dockerfile#L2), [9.0](https://github.com/sitecoreops/sitecore-images/blob/master/images/9.0.0%20rev.%20171002/windowsservercore-1709/sitecore-base/Dockerfile#L2))
- 4.7.2 is used for win 1803 and all the others ([8.2.3](https://github.com/sitecoreops/sitecore-images/blob/master/images/8.2%20rev.%20170407/windowsservercore-1803/Sitecore/Dockerfile#L2), [9.1.0](https://github.com/sitecoreops/sitecore-images/blob/master/images/9.1.0%20rev.%20001564/windowsservercore-1803/sitecore-base/Dockerfile#L11) etc.)

Is this done for purpose? I noticed that if I prune my images I have to download _both_ aspnet versions. That's not a big deal but I'm just wondering if it's really needed and whether one can save some time/Gbs avoiding that.

Please take a look on the available [aspnet tags](https://mcrflowprodcentralus.cdn.mscr.io/mcrprod/dotnet/framework/aspnet?P1=1557239380&P2=1&P3=1&P4=l8SuTSenSoJgr94JdeQ8tHQJppFbtKyrA%2FuqGKooCXs%3D&se=2019-05-07T14%3A29%3A40Z&sig=96KJg4AWUmx1It9YgHNu5j%2FIXmVprYKjDoILSpr%2BFso%3D&sp=r&sr=b&sv=2015-02-21):

```
    "20181113-4.7.1-windowsservercore-1709",
    "20181113-4.7.1-windowsservercore-ltsc2016",
    "20181113-4.7.2-windowsservercore-1709",
    "20181113-4.7.2-windowsservercore-1803",
    "20181113-4.7.2-windowsservercore-ltsc2016",
    "20181113-4.7.2-windowsservercore-ltsc2019",
```

Framework 4.7.2 is available for both win 1709 and 1803 meaning we can update all the images and get rid of 4.7.1 at all. Does it makes sense? Please let me know if I should come up with a PR fixing that.

**Comment by pbering** [comment]
Hi there, when I started on these images I used the .NET version that was support for a given Sitecore version according the [Sitecore compatibility table](https://kb.sitecore.net/articles/087164). But overtime this drifted a bit :) Since all 8 and 9 versions works fine on 4.7.2 as the .NET framework is pretty good at being backward compatible, a PR for aligning 8.2 and 9.x on 4.7.2 would highly appreciated.

**Comment by pbering** [comment]
BTW I'm considering to retire all the 1709 and ltsc2016 images by moving them into a "retired" folder so they would be something that you need to build explicit (like with the new variants). Microsoft has [stopped supporting .NET on 1709](https://github.com/Microsoft/dotnet-framework-docker/issues/259). So aligning on 4.7.2 makes sense to do before they are retired.
