### ISSUE TITLE
mssql-developer:2017-windowsservercore-ltsc2019 doesn't seem to exist

### ISSUE THREAD

**Issue by spiraljacobs** [sitecoreops/sitecore-images#41]
When trying to build a 9.1.1 installation, I'm receiving this error:

### Processing 'sitecore-xm1-sqldev:9.1.1-windowsservercore-ltsc2019'...
Sending build context to Docker daemon  443.4MB
Step 1/5 : FROM mssql-developer:2017-windowsservercore-ltsc2019
pull access denied for mssql-developer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Failed.
At C:\Docker\sitecore-images\modules\SitecoreImageBuilder\SitecoreImageBuilder.psm1:158 char:70
+ ... CODE -ne 0 | Where-Object { $_ } | ForEach-Object { throw "Failed." }
+                                                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed.

**Comment by pbering** [comment]
Hi, which tags have you defined in the `-Tags` parameter? Should like you have something other than *, so you need to have base images build as well. Tthere will soon be merged a change that does that automatically but until then you can do like this: 

```
-Tags "sitecore-openjdk:*", "sitecore-base:9.1.1-*", "mssql-developer:2017-*" 
```

**Comment by spiraljacobs** [comment]
@pbering thanks for the reply!
I was following this tutorial: http://blog.martinmiles.net/post/starting-with-docker-and-sitecore 
The idea was to get a working sitecore docker container setup going to ease other developers on the team, particularly front end devs, up and running quickly.
I'm not sure which tag to specify, to tell you the truth, as it was based off the build script supplied in that site: 
```
"pass" | docker login --username myusername --password-stdin

# Load module
Import-Module (Join-Path $PSScriptRoot "\modules\SitecoreImageBuilder") -Force

# Build and push
SitecoreImageBuilder\Invoke-Build `
    -Path (Join-Path $PSScriptRoot "\images") `
    -InstallSourcePath "c:\Docker\Install\9.1.1" `
    -Registry "myregistry" `
    -Tags "*" `
    -PushMode "WhenChanged"
```
The failure is specifically around `### Processing 'sitecore-xm1-sqldev:9.1.1-windowsservercore-ltsc2019'...
Sending build context to Docker daemon  443.4MB
Step 1/5 : FROM mssql-developer:2017-windowsservercore-ltsc2019
pull access denied for mssql-developer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

All the other images specified seem fine, but if I try to just docker pull mssql-developer:2017-windowsservercore-ltsc2019, it doesn't exist.

**Comment by pbering** [comment]
The `mssql-developer:2017-windowsservercore-ltsc2019` image is not in any public registries but build here and defined in https://github.com/sitecoreops/sitecore-images/blob/master/images/mssql-developer-2017/windowsservercore-ltsc2019/build.json. Not sure why it's not build first as it should. Can you please try to run 

```
SitecoreImageBuilder\Invoke-Build `
    -Path (Join-Path $PSScriptRoot "\images") `
    -InstallSourcePath "c:\Docker\Install\9.1.1" `
    -Registry "myregistry" `
    -Tags "*" `
    -PushMode "WhenChanged" -WhatIf
```
(notice the -WhatIf parameter) and paste the output here?

**Comment by spiraljacobs** [comment]
It spit out a list of tags:

```
Tag                                                                    Include Priority Base
---                                                                    ------- -------- ----
sitecore-openjdk:8-nanoserver-1709                                        True      110 {mcr.microsoft.com/windows/s...
sitecore-openjdk:8-nanoserver-1803                                        True      110 {mcr.microsoft.com/windows/s...
sitecore-openjdk:8-nanoserver-1809                                        True      110 {mcr.microsoft.com/windows/s...
sitecore-base:9.1.1-windowsservercore-ltsc2019                            True      120 {mcr.microsoft.com/windows/s...
sitecore-xm1-sqldev:9.1.1-windowsservercore-ltsc2019                      True      130 mssql-developer:2017-windows...
sitecore-xp-sqldev:9.1.1-windowsservercore-ltsc2019                       True      160 microsoft/mssql-server-windo...
sitecore-xp-base:9.1.1-windowsservercore-ltsc2019                         True      170 {mcr.microsoft.com/windows/s...
sitecore-xp-xconnect:9.1.1-windowsservercore-ltsc2019                     True      180 {mcr.microsoft.com/windows/s...
sitecore-xm1-solr:9.1.1-nanoserver-1809                                   True     1000 {sitecore-base:9.1.1-windows...
sitecore-xp-solr:9.1.1-nanoserver-1809                                    True     1000 {sitecore-base:9.1.1-windows...
sitecore-xm1-cd:9.1.1-windowsservercore-ltsc2019                          True     1000 {mcr.microsoft.com/windows/s...
sitecore-xm1-cm:9.1.1-windowsservercore-ltsc2019                          True     1000 {mcr.microsoft.com/windows/s...
sitecore-xp-cd:9.1.1-windowsservercore-ltsc2019                           True     1000 {mcr.microsoft.com/windows/s...
sitecore-xp-standalone:9.1.1-windowsservercore-ltsc2019                   True     1000 {mcr.microsoft.com/windows/s...
sitecore-xp-xconnect-automationengine:9.1.1-windowsservercore-ltsc2019    True     1000 {sitecore-xp-xconnect:9.1.1-...
sitecore-xp-xconnect-indexworker:9.1.1-windowsservercore-ltsc2019         True     1000 {sitecore-xp-xconnect:9.1.1-...
```

Hopefully that helps!

**Comment by pbering** [comment]
that is strange! Seems like you are missing some files on disk, do you have the "/images/mssql-developer-2017/windowsservercore-ltsc2019/build.json" file?

**Comment by spiraljacobs** [comment]
Oh man....that might be it - in the tutorial I linked above, the author removes all the folders from this repo other than the 9.1.1 folder and the jdk folder.  
Ugh.   I put the folder back for the sql server image, and yeah, I think it's working.  I'll keep you posted.

Thanks for the tremendous help!  Stumbling my way through this :)

**Comment by pbering** [comment]
no problem 👍 

Will close this for now :)
