### ISSUE TITLE
Error building image for sitecore-xp-cd:9.1.1-windowsservercore-ltsc2019

### ISSUE THREAD

**Issue by sgisbert** [sitecoreops/sitecore-images#50]
Hi,
thanks for the amazing work you are doing here! 
I am building the images for Sitecore 9.1.1, and everything was going fine so far, until I get to build the XP-CD image: I am getting an error related to the Powershell executed on Dockerfile.

I cloned the repo at "C:\Docker\sitecore-images\"
I have downloaded the Sitecore packages and the license.xml locally
I have built the base images succesfully

This the command that fails:
`Invoke-Build -Path "C:\Docker\sitecore-images\images\9.1.1 rev. 002459\windowsservercore\sitecore-xp-cd" -InstallSourcePath $PackageSourcesPath -Registry sgisbert -PushMode Never -Tags *:9.1.1-windowsservercore-ltsc2019 -Verbose`

And this is the output generated: [exit.txt](https://github.com/sitecoreops/sitecore-images/files/3244075/exit.txt)

Any help will be much appreciated.

Thanks.

**Comment by pbering** [comment]
Hi there, thank you for your kind words!

From the error in your output `New-Object : Exception calling ".ctor" with "3" argument(s): "End of Central 
Directory record could not be found."
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Arch
ive\Microsoft.PowerShell.Archive.psm1:934 char:23` it looks like some kind of internal error in PowerShell command used.

Can you verify that the zip file `\images\9.1.1 rev. 002459\windowsservercore\Sitecore 9.1.1 rev. 002459 (WDP XP1 packages).zip` works and is not corrupted by opening it and unzip it somewhere else?

Also check that you only have that 1 zip file in the folder, I can see in you output that the Docker context size `Sending build context to Docker daemon  4.492MB` is larger than normal (~1.5GB)

**Comment by sgisbert** [comment]
That was it: the sitecore zip package was damaged. I downloaded it again and was able to build the image so far.

Thanks again!

**Comment by pbering** [comment]
Great! Enjoy :)
